apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
spec:
  selector:
      matchLabels:
        app: teastore
        run: teastore-db
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-db
    spec:
      containers:
      - name: teastore-db
        image: teastore-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: teastore-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-registry
spec:
  selector:
      matchLabels:
        app: teastore
        run: teastore-registry
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-registry
    spec:
      containers:
      - name: teastore-registry
        image: teastore-registry:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: USE_POD_IP
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-registry
  labels:
    app: teastore
    run: teastore-registry
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
spec:
  selector:
      matchLabels:
        app: teastore
        run: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-persistence
    spec:
      containers:
      - name: teastore-persistence
        image: teastore-persistence:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        - name: DB_HOST
          value: "teastore-db"
        - name: DB_PORT
          value: "3306"
        - name: LOG_TO_FILE
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-auth
spec:
  selector:
      matchLabels:
        app: teastore
        run: teastore-auth
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-auth
    spec:
      containers:
      - name: teastore-auth
        image: teastore-auth:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        - name: LOG_TO_FILE
          value: "true"
        volumeMounts:
        - name: log-volume
          mountPath: /kieker/logs/
      volumes:
        - name: log-volume
          hostPath:
            path: /home/ginesmr/Music/TeaStore/kieker-results/
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
spec:
  selector:
      matchLabels:
        app: teastore
        run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-image
    spec:
      containers:
      - name: teastore-image
        image: teastore-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        - name: LOG_TO_FILE
          value: "true"
        volumeMounts:
        - name: log-volume
          mountPath: /kieker/logs/
      volumes:
        - name: log-volume
          hostPath:
            path: /home/ginesmr/Music/TeaStore/kieker-results/
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-recommender
spec:
  selector:
      matchLabels:
        app: teastore
        run: teastore-recommender
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-recommender
    spec:
      containers:
      - name: teastore-recommender
        image: teastore-recommender:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        - name: LOG_TO_FILE
          value: "true"
        volumeMounts:
        - name: log-volume
          mountPath: /kieker/logs/
      volumes:
        - name: log-volume
          hostPath:
            path: /home/ginesmr/Music/TeaStore/kieker-results/
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-webui
spec:
  selector:
      matchLabels:
        app: teastore
        run: teastore-webui
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-webui
    spec:
      containers:
      - name: teastore-webui
        image: teastore-webui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        - name: LOG_TO_FILE
          value: "true"
        volumeMounts:
        - name: log-volume
          mountPath: /kieker/logs/
      volumes:
        - name: log-volume
          hostPath:
            path: /home/ginesmr/Music/TeaStore/kieker-results/
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
  labels:
    app: teastore
    run: teastore-webui
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    run: teastore-webui


