apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
spec:
  selector:
      matchLabels:
        app: teastore
        run: teastore-db
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-db
    spec:
      containers:
      - name: teastore-db
        image: teastore-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: teastore-db
