apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
spec:
  selector:
      matchLabels:
        app: teastore
        run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-image
    spec:
      containers:
      - name: teastore-image
        image: teastore-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        - name: LOG_TO_FILE
          value: "true"
