apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-demo-server
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-demo-server
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-demo-server
    spec:
      containers:
      - name: teastore-demo-server
        image: teastore-demo-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-demo-server
  labels:
    app: teastore
    run: teastore-demo-server
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30082
    protocol: TCP
    name: teastore-demo-webui-port
  selector:
    run: teastore-demo-server
---
# DNS name service to send the logs over the internal 
# k8s network
apiVersion: v1
kind: Service
metadata:
  name: socket-log-server
  labels:
    app: teastore
    run: socket-log-server
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    run: teastore-demo-server
